# Generated by Django 5.0.1 on 2024-01-30 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('amount_of_money', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_character', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('date_of_birth', models.DateField(null=True)),
                ('patronus', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=204.55505791203262, max_digits=6)),
                ('xp_points', models.IntegerField(default=5)),
                ('current_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wizard_current_owner', to='cards.user')),
                ('previous_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wizard_previous_owner', to='cards.user')),
            ],
        ),
    ]
